/** Hằng số nghiệp vụ (role, status…). */
export const AppConstant = Object.freeze({
  ROLE_CUSTOMER: "CUSTOMER",
  ROLE_ADMIN: "ADMIN",
  STATUS_ACTIVE: "ACTIVE",
  STATUS_INACTIVE: "INACTIVE",
  ORDER_PENDING: "PENDING",
  ORDER_PAYMENT_PENDING: "PAYMENT_PENDING",
  ORDER_CONFIRMED: "CONFIRMED",
  ORDER_PROCESSING: "PROCESSING",
  ORDER_SHIPPING: "SHIPPING",
  ORDER_DELIVERED: "DELIVERED",
  ORDER_CANCELLED: "CANCELLED",
  ORDER_PAYMENT_FAILED: "PAYMENT_FAILED"
});
