/**
 * Mã lỗi hệ thống (khớp backend ErrorConstant).
 * Chỉ dùng nội bộ / map message — không hiển thị lên UI.
 */
export const ErrorConstant = Object.freeze({
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CATEGORY_EXISTS: "CATEGORY_EXISTS",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_SERVICE_ERROR: "PRODUCT_SERVICE_ERROR",
  CART_EMPTY: "CART_EMPTY",
  CART_ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_SERVICE_ERROR: "PAYMENT_SERVICE_ERROR",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_STOCK: "INVALID_STOCK",
  INVENTORY_NOT_FOUND: "INVENTORY_NOT_FOUND"
});
