spring.boot.admin.client.url=${ADMIN_SERVER_URI:http://localhost:8088}
spring.boot.admin.client.instance.service-base-url=http://127.0.0.1:${server.port:8080}
management.endpoints.web.exposure.include=health,info,logfile,loggers
management.endpoint.logfile.enabled=true
